MODULE SPEC_VIEW_MOD
  IMPLICIT NONE
TYPE SPEC_VIEW
   REAL(KIND=8), POINTER :: P(:)
END TYPE SPEC_VIEW

TYPE SPEC_DATA
   REAL(KIND=8), ALLOCATABLE :: P(:)
END TYPE SPEC_DATA

CONTAINS

SUBROUTINE ALLOCATE_SPECPTRS(SPECPTRS, NFIELDS, NSMAX)

   TYPE(SPEC_DATA), INTENT(OUT), ALLOCATABLE :: SPECPTRS(:)
   INTEGER, INTENT(IN) :: NFIELDS, NSMAX

   INTEGER :: JFLD
   ALLOCATE(SPECPTRS(NFIELDS))
   DO JFLD=1, NFIELDS
      ALLOCATE(SPECPTRS(JFLD)%P(NSMAX))
   ENDDO

END SUBROUTINE ALLOCATE_SPECPTRS

SUBROUTINE WRAP(SPECPTRS,YDSP, NFIELDS)
      TYPE(SPEC_DATA), INTENT(IN), TARGET :: SPECPTRS(:)
      TYPE(SPEC_VIEW), INTENT(INOUT) :: YDSP(:)
      INTEGER, INTENT(IN) :: NFIELDS
      INTEGER :: JFLD

      DO JFLD=1, NFIELDS
            YDSP(JFLD)%P => SPECPTRS(JFLD)%P
      ENDDO
END SUBROUTINE WRAP


!-----------------------------------------------------------------------------
SUBROUTINE  PRFI1B_REF (PIA,PSPEC,NFIELDS,NSMAX,DNUMP)

REAL(KIND=8), INTENT(OUT) :: PIA(:,:,:)
REAL(KIND=8), INTENT(IN) :: PSPEC(:,:)

INTEGER, INTENT(IN) :: NFIELDS, NSMAX, DNUMP

INTEGER :: JFLD,JN, KMLOC

! This is the reference version, mimicking PRFI1B from ecTrans 

!$ACC PARALLEL LOOP COLLAPSE(3) PRESENT(PSPEC,PIA) PRIVATE(JFLD,JN,KMLOC) FIRSTPRIVATE(NFIELDS,NSMAX,DNUMP) DEFAULT(NONE)
DO KMLOC=1, DNUMP
  DO JN=1, NSMAX
      DO JFLD=1, NFIELDS
            PIA(JFLD,JN,KMLOC) = PSPEC(JFLD,JN)
      ENDDO
  ENDDO
ENDDO

END SUBROUTINE   PRFI1B_REF

SUBROUTINE PRFIB_V1 (PIA,YDSP,NFIELDS,NSMAX,DNUMP)

TYPE(SPEC_VIEW), INTENT(IN) :: YDSP(:)
REAL(KIND=8), INTENT(OUT) :: PIA(:,:,:)
INTEGER, INTENT(IN) :: NFIELDS, NSMAX, DNUMP

INTEGER :: JFLD,JN, KMLOC

! This is a direct adaptation of the reference version using YDSP instead of PSPEC


!$ACC PARALLEL LOOP COLLAPSE(3) PRESENT(PIA, YDSP) PRIVATE(JFLD,JN,KMLOC) DEFAULT(NONE) FIRSTPRIVATE(NFIELDS,NSMAX,DNUMP) 
DO KMLOC=1, DNUMP
  DO JN=1, NSMAX
      DO JFLD=1, NFIELDS
            PIA(JFLD,JN,KMLOC) = YDSP(JFLD)%P(JN)
      ENDDO
  ENDDO
ENDDO

END SUBROUTINE PRFIB_V1

SUBROUTINE PRFIB_V2 (PIA,YDSP,NFIELDS,NSMAX,DNUMP)

TYPE(SPEC_VIEW), INTENT(IN) :: YDSP(:)
REAL(KIND=8), INTENT(OUT) :: PIA(:,:,:)
INTEGER, INTENT(IN) :: NFIELDS, NSMAX, DNUMP

INTEGER :: JFLD,JN, KMLOC

! This is an version  mimicking EXCHANGE_MS_MOD.F90 for IAL


!$ACC PARALLEL PRIVATE(KMLOC,JN,JFLD) PRESENT(YDSP, PIA) DEFAULT(NONE) VECTOR_LENGTH(32) FIRSTPRIVATE(NFIELDS,NSMAX,DNUMP)
!$ACC LOOP GANG VECTOR COLLAPSE(2)  
DO KMLOC=1, DNUMP
  DO JN=1, NSMAX
      DO JFLD=1, NFIELDS
            PIA(JFLD,JN,KMLOC) = YDSP(JFLD)%P(JN)
      ENDDO
  ENDDO
ENDDO
 !$ACC END PARALLEL
END SUBROUTINE PRFIB_V2

SUBROUTINE PRFIB_V3 (PIA,YDSP,NFIELDS,NSMAX,DNUMP)

TYPE(SPEC_VIEW), INTENT(IN) :: YDSP(:)
REAL(KIND=8), INTENT(OUT) :: PIA(:,:,:)
INTEGER, INTENT(IN) :: NFIELDS, NSMAX, DNUMP

REAL(KIND=8), POINTER :: ZZ(:)
INTEGER :: JFLD,JN, KMLOC

! This is a version keeping YDSP on CPU

DO JFLD=1, NFIELDS
      ZZ => YDSP(JFLD)%P
      !$ACC PARALLEL LOOP COLLAPSE(2) PRESENT(PIA) PRIVATE(JFLD,JN,KMLOC) FIRSTPRIVATE(NSMAX,DNUMP) PRESENT(ZZ)
      DO KMLOC=1, DNUMP
            DO JN=1, NSMAX
              PIA(JFLD,JN,KMLOC) = ZZ(JN)
            ENDDO
      ENDDO
ENDDO

END SUBROUTINE PRFIB_V3

!---------------------------------------------------------
SUBROUTINE  UPDSP_REF (PIA,PSPEC,NFIELDS,NSMAX,DNUMP)

REAL(KIND=8), INTENT(IN) :: PIA(:,:,:)
REAL(KIND=8), INTENT(OUT) :: PSPEC(:,:)

INTEGER, INTENT(IN) :: NFIELDS, NSMAX, DNUMP

INTEGER :: JFLD,JN, KMLOC

! This is the reference version, mimicking UPDSP from ecTrans 


!$ACC PARALLEL LOOP COLLAPSE(3) PRESENT(PSPEC,PIA) PRIVATE(JFLD,JN,KMLOC) FIRSTPRIVATE(NFIELDS,NSMAX,DNUMP) DEFAULT(NONE)
DO KMLOC=1, DNUMP
  DO JN=1, NSMAX
      DO JFLD=1, NFIELDS
            PSPEC(JFLD,JN) = PIA(JFLD,JN,KMLOC)
      ENDDO
  ENDDO
ENDDO

END SUBROUTINE  UPDSP_REF

SUBROUTINE UPDSP_V1 (PIA,YDSP,NFIELDS,NSMAX,DNUMP)

REAL(KIND=8), INTENT(IN) :: PIA(:,:,:)
TYPE(SPEC_VIEW), INTENT(IN) :: YDSP(:)
INTEGER, INTENT(IN) :: NFIELDS, NSMAX, DNUMP
INTEGER :: JFLD,JN,KMLOC

! This is a direct adaptation of the reference version using YDSP instead of PSPEC

!$ACC PARALLEL LOOP COLLAPSE(3) PRESENT(PIA,YDSP) PRIVATE(JFLD,JN,KMLOC)  DEFAULT(NONE) FIRSTPRIVATE(NFIELDS,NSMAX,DNUMP)

DO KMLOC=1, DNUMP
  DO JN=1, NSMAX
      DO JFLD=1, NFIELDS
            YDSP(JFLD)%P(JN) = PIA(JFLD,JN,KMLOC)
      ENDDO
  ENDDO
ENDDO
 
END SUBROUTINE UPDSP_V1

SUBROUTINE UPDSP_V2 (PIA,YDSP,NFIELDS,NSMAX,DNUMP)

REAL(KIND=8), INTENT(IN) :: PIA(:,:,:)
TYPE(SPEC_VIEW), INTENT(IN) :: YDSP(:)
INTEGER, INTENT(IN) :: NFIELDS, NSMAX, DNUMP
INTEGER :: JFLD,JN,KMLOC

! This is an version  mimicking EXCHANGE_MS_MOD.F90 for IAL

!$ACC PARALLEL PRIVATE(KMLOC,JN,JFLD) PRESENT(YDSP,PIA) DEFAULT(NONE) VECTOR_LENGTH(32) FIRSTPRIVATE(NFIELDS,NSMAX,DNUMP)
!$ACC LOOP GANG VECTOR COLLAPSE(2)
DO KMLOC=1, DNUMP
  DO JN=1, NSMAX
      DO JFLD=1, NFIELDS
            YDSP(JFLD)%P(JN) = PIA(JFLD,JN,KMLOC)
      ENDDO
  ENDDO
ENDDO
 !$ACC END PARALLEL
END SUBROUTINE UPDSP_V2


SUBROUTINE UPDSP_V3 (PIA,YDSP,NFIELDS,NSMAX,DNUMP)

REAL(KIND=8), INTENT(IN) :: PIA(:,:,:)
TYPE(SPEC_VIEW), INTENT(IN) :: YDSP(:)
INTEGER, INTENT(IN) :: NFIELDS, NSMAX, DNUMP
INTEGER :: JFLD,JN,KMLOC
REAL(KIND=8), POINTER :: ZZ(:)

! This is a version keeping YDSP on CPU

DO JFLD=1, NFIELDS
      ZZ => YDSP(JFLD)%P
      !$ACC PARALLEL LOOP COLLAPSE(2) PRESENT(PIA) PRIVATE(JFLD,JN,KMLOC) FIRSTPRIVATE(NSMAX,DNUMP)  PRESENT(ZZ)
      DO KMLOC=1, DNUMP
            DO JN=1, NSMAX
                  ZZ(JN) = PIA(JFLD,JN,KMLOC)
            ENDDO
      ENDDO
ENDDO

END SUBROUTINE UPDSP_V3



END MODULE SPEC_VIEW_MOD

PROGRAM COPY_ARRAYS

   USE SPEC_VIEW_MOD
   USE OMP_LIB

IMPLICIT NONE

REAL(KIND=8), ALLOCATABLE :: PIA(:,:,:)
REAL(KIND=8), ALLOCATABLE :: PSPEC(:,:)
INTEGER :: NFIELDS, NSMAX, DNUMP, ITER, NITER
TYPE(SPEC_VIEW), ALLOCATABLE :: YDSP(:)
TYPE(SPEC_DATA), ALLOCATABLE :: SPECPTRS(:)
REAL(KIND=8) :: TS,TE
NITER = 1000
NFIELDS = 100
NSMAX = 200
DNUMP = 100

CALL READ_ARGS(NFIELDS,NSMAX,DNUMP,NITER)
WRITE (*,*) '** Parameters **'
WRITE (*,*) ' NFIELDS:',NFIELDS
WRITE (*,*) ' NSMAX:',NSMAX
WRITE (*,*) ' DNUMP:',DNUMP
WRITE (*,*) ' NITER:',NITER

ALLOCATE(PIA(NFIELDS,NSMAX,DNUMP))
ALLOCATE(PSPEC(NFIELDS,NSMAX))

CALL ALLOCATE_SPECPTRS(SPECPTRS,NFIELDS,NSMAX)
ALLOCATE(YDSP(NFIELDS))
 
CALL WRAP(SPECPTRS,YDSP,NFIELDS)
!$ACC ENTER DATA COPYIN(PIA,PSPEC,SPECPTRS,YDSP)
DO ITER=1, NFIELDS
   !$ACC ENTER DATA COPYIN(SPECPTRS(ITER)%P)
   !$ACC ENTER DATA ATTACH(YDSP(ITER)%P)
ENDDO
!$ACC DATA PRESENT(PIA,PSPEC,SPECPTRS,YDSP)

!------------------------------
!WARMUP
CALL PRFI1B_REF(PIA,PSPEC, NFIELDS,NSMAX,DNUMP)
CALL UPDSP_REF(PIA,PSPEC,NFIELDS,NSMAX,DNUMP)
!------------------------------
WRITE(*,*)
WRITE(*,*) "** PRFI1B **"
TS=OMP_GET_WTIME()
DO ITER=1, NITER
      CALL  PRFI1B_REF(PIA,PSPEC, NFIELDS,NSMAX,DNUMP)
ENDDO
TE=OMP_GET_WTIME()
WRITE (*,'(A,F8.2,A)') '  PRFI1B_REF:',GET_TIME(TS,TE,NFIELDS,NSMAX,DNUMP,NITER)
!------------------------------
TS=OMP_GET_WTIME()
DO ITER=1, NITER
      CALL PRFIB_V1(PIA,YDSP,NFIELDS,NSMAX,DNUMP)
ENDDO
TE=OMP_GET_WTIME()
WRITE (*,'(A,F8.2,A)') '  PRFIB_V1:',GET_TIME(TS,TE,NFIELDS,NSMAX,DNUMP,NITER)

!------------------------------
TS=OMP_GET_WTIME()
DO ITER=1, NITER
      CALL PRFIB_V2(PIA,YDSP,NFIELDS,NSMAX,DNUMP)
ENDDO
TE=OMP_GET_WTIME()
WRITE (*,'(A,F8.2,A)') '  PRFIB_V2:',GET_TIME(TS,TE,NFIELDS,NSMAX,DNUMP,NITER)
!------------------------------
TS=OMP_GET_WTIME()
DO ITER=1, NITER
      CALL PRFIB_V3(PIA,YDSP,NFIELDS,NSMAX,DNUMP)
ENDDO
TE=OMP_GET_WTIME()
WRITE (*,'(A,F8.2,A)') '  PRFIB_V3:',GET_TIME(TS,TE,NFIELDS,NSMAX,DNUMP,NITER)
!------------------------------
WRITE(*,*)
WRITE(*,*) "** UPDSP **"
TS=OMP_GET_WTIME()
DO ITER=1, NITER
      CALL UPDSP_REF(PIA,PSPEC,NFIELDS,NSMAX,DNUMP)
ENDDO
TE=OMP_GET_WTIME()
WRITE (*,'(A,F8.2,A)') '  UPDSP_REF:',GET_TIME(TS,TE,NFIELDS,NSMAX,DNUMP,NITER)
!------------------------------
TS=OMP_GET_WTIME()
DO ITER=1, NITER
      CALL UPDSP_V1(PIA,YDSP,NFIELDS,NSMAX,DNUMP)
ENDDO
TE=OMP_GET_WTIME()
WRITE (*,'(A,F8.2,A)') '  UPDSP_V1:',GET_TIME(TS,TE,NFIELDS,NSMAX,DNUMP,NITER)
!------------------------------
TS=OMP_GET_WTIME()
DO ITER=1, NITER
      CALL UPDSP_V2(PIA,YDSP,NFIELDS,NSMAX,DNUMP)
ENDDO
TE=OMP_GET_WTIME()
WRITE (*,'(A,F8.2,A)') '  UPDSP_V2:',GET_TIME(TS,TE,NFIELDS,NSMAX,DNUMP,NITER)
!------------------------------
TS=OMP_GET_WTIME()
DO ITER=1, NITER
      CALL  UPDSP_V3(PIA,YDSP, NFIELDS,NSMAX,DNUMP)
ENDDO
TE=OMP_GET_WTIME()
WRITE (*,'(A,F8.2,A)') '  UPDSP_V3:',GET_TIME(TS,TE,NFIELDS,NSMAX,DNUMP,NITER)
!------------------------------


!$ACC END DATA
DO ITER=1, NFIELDS
   !$ACC EXIT DATA DETACH(YDSP(ITER)%P)
   !$ACC EXIT DATA DELETE(SPECPTRS(ITER)%P)
ENDDO
!$ACC EXIT DATA DELETE(PIA,PSPEC,SPECPTRS,YDSP)


CONTAINS

SUBROUTINE READ_ARGS(KFIELD,KN,KMLOC,COUNT)
      INTEGER, INTENT(OUT) :: KFIELD, KN, KMLOC,COUNT

      CHARACTER(LEN=256) :: CARG

      IF (COMMAND_ARGUMENT_COUNT() == 0) THEN
          RETURN
      ENDIF      
      
      IF (COMMAND_ARGUMENT_COUNT() /= 4) THEN
            WRITE(*,*) "Usage: main.x KFIELD KN KMLOC COUNT"
            STOP
      ENDIF
      CALL GET_COMMAND_ARGUMENT(1,CARG)
      READ(CARG,*) KFIELD

      CALL GET_COMMAND_ARGUMENT(2,CARG)
      READ(CARG,*) KN

      CALL GET_COMMAND_ARGUMENT(3,CARG)
      READ(CARG,*) KMLOC

      CALL GET_COMMAND_ARGUMENT(4,CARG)
      READ(CARG,*) COUNT
END SUBROUTINE READ_ARGS

FUNCTION GET_TIME(START,END,KFIELDS,KSPEC2,KNUMP,COUNT)
      REAL(KIND=8) :: GET_TIME
      REAL(KIND=8) :: START,END
      INTEGER, INTENT(IN) :: KFIELDS, KSPEC2, KNUMP, COUNT
      GET_TIME = 1E12 * (END-START) / (KFIELDS * KSPEC2 * KNUMP * COUNT)
END FUNCTION GET_TIME
END PROGRAM

